### ISSUE TITLE
无法开启rss模块

### ISSUE THREAD

**Issue by Raven-tu** [Ray-Eldath/Avalon#12]
关闭rss模块可正常运行但是开启rss模块会卡在启动界面
日志显示

> 
18:53:11.462 [main] INFO  avalon.tool.ServiceChecker - Now checking usability of services...
18:53:11.465 [main] INFO  avalon.tool.ServiceChecker -    CoolQBackend: Accessible
18:53:11.780 [main] INFO  avalon.tool.ServiceChecker -    Hitokotor: Accessible
18:53:11.780 [main] INFO  avalon.tool.ServiceChecker - Services all checked.
18:55:33.897 [main] INFO  avalon.tool.ServiceChecker - Now checking usability of services...
18:55:33.900 [main] INFO  avalon.tool.ServiceChecker -    CoolQBackend: Accessible
18:55:34.322 [main] INFO  avalon.tool.ServiceChecker -    Hitokotor: Accessible
18:55:34.322 [main] INFO  avalon.tool.ServiceChecker - Services all checked.
18:55:49.256 [main] INFO  avalon.tool.ServiceChecker - Now checking usability of services...
18:55:49.259 [main] INFO  avalon.tool.ServiceChecker -    CoolQBackend: Accessible
18:55:49.591 [main] INFO  avalon.tool.ServiceChecker -    Hitokotor: Accessible
18:55:49.591 [main] INFO  avalon.tool.ServiceChecker - Services all checked.
18:55:59.063 [main] INFO  avalon.tool.ServiceChecker - Now checking usability of services...
18:55:59.066 [main] INFO  avalon.tool.ServiceChecker -    CoolQBackend: Accessible
18:55:59.360 [main] INFO  avalon.tool.ServiceChecker -    Hitokotor: Accessible
18:55:59.361 [main] INFO  avalon.tool.ServiceChecker - Services all checked.
18:58:46.387 [main] INFO  avalon.tool.ServiceChecker - Now checking usability of services...
18:58:46.391 [main] INFO  avalon.tool.ServiceChecker -    CoolQBackend: Accessible
18:58:46.816 [main] INFO  avalon.tool.ServiceChecker -    Hitokotor: Accessible
18:58:46.817 [main] INFO  avalon.tool.ServiceChecker - Services all checked.
> 
config.json rss模块
> "RSS": {
	  "enable": true,
	  "feed": [
		"http://ice1000.org/feed.xml"
	  ]
	}
![Snipaste_2019-05-16_19-00-59](https://user-images.githubusercontent.com/23189615/57849446-e4338380-780d-11e9-8a12-7e2810acd2be.png)

**Comment by Ray-Eldath** [comment]
居然**真的**会有人去部署我这个项目...
感谢反馈。我会尽快修复并发布hotfix

**Comment by Ray-Eldath** [comment]
已经在新版本[v1.3.1](https://github.com/Ray-Eldath/Avalon/releases/tag/v1.3.1)中修复。

**Comment by Raven-tu** [comment]
XD
