### ISSUE TITLE
暂时停止游戏系统的开发

### ISSUE THREAD

**Issue by Ray-Eldath** [Ray-Eldath/Avalon#2]
由于现有API系统太过于冗杂，非常需要改进。现暂停游戏系统的开发，专注于优化API的设计以降低剧本编写难度。
就这样。
（有谁有好的构想不？）

**Comment by ice1000** [comment]
随便说说


惰性加载，避免那种十几个G的资源一次加进来把JVM搞死
可视化编辑器导出\[代码/配置文件然后代码读取\]

**Comment by Ray-Eldath** [comment]
See [Avalon-Game](https://github.com/Ray-Eldath/Avalon-Game).
