### ISSUE TITLE
尽快更新至release: >v0.0.1b

### ISSUE THREAD

**Issue by Ray-Eldath** [Ray-Eldath/Avalon#3]
由于腾讯~~脑子~~的问题，可能删掉了一个至关重要、获取`sender_uid`的API，导致[Mojo-Webqq](https://github.com/sjdy521/Mojo-Webqq)POST消息工作不正常（一直报404，已向开发者提交[Issue](https://github.com/sjdy521/Mojo-Webqq/issues/128)），目前我连 测试 都没法完成... ...
因此最近开发可能会受到影响。

---

出于我已经给项目加上JitPack，而原先的v0.0.1-beta版本未将各模块分开架构，依赖处理较为不便，因此最近可能发布一个**非正式的patch版本**，由于上述原因可能无法正常测试，请慎重选择更新。

---
**！！！！！** 请以最新comment为准。

以上。
Ray Eldath.

**Comment by Ray-Eldath** [comment]
**！！** Patch版本已经发布，请尽快更新至`v0.0.1b`版本。
以上。
Ray Eldath.

**Comment by ice1000** [comment]
Switched to CoolQ, there's no more API problem

**Comment by Ray-Eldath** [comment]
**！！** [5a76223](https://github.com/Ray-Eldath/Avalon/commit/5a7622311b99e088c8ede9982ab7d4299795fdde)及`v0.0.1b`以后的`release`已经基于Cooq协议重写了服务模块，此问题在新版本中已不存在。
**请尽快更新！**

以上。
Ray Eldath

**Comment by ice1000** [comment]
Good

**Comment by ice1000** [comment]
Admire

**Comment by ice1000** [comment]
Admire
